from __future__ import annotations

import csv
import tempfile
import unittest
from pathlib import Path
from types import SimpleNamespace

from scripts.build_enriched_release import run_build


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def write_csv(path: Path, fieldnames: list[str], rows: list[dict[str, str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


class BuildEnrichedReleaseTests(unittest.TestCase):
    def _args(self, root: Path, **overrides: object) -> SimpleNamespace:
        values = {
            "input_master": str(root / "results" / "published-20260326" / "publishable_master_games.csv"),
            "input_issues": str(root / "results" / "published-20260326" / "publishable_issue_titles.csv"),
            "baseline_enriched_master": str(root / "results" / "enriched-20260325" / "enriched_master_games.csv"),
            "output_dir": str(root / "results" / "enriched-20260326"),
            "manual_rejections": str(root / "data" / "manual_rejections.csv"),
            "cache_db": str(root / "results" / "enrichment.sqlite"),
            "resume": False,
            "refresh_cache": False,
            "limit": None,
            "only_unmatched": False,
            "only_ambiguous": False,
            "manual_alias_overrides": str(root / "data" / "manual_alias_overrides.csv"),
            "manual_entity_overrides": str(root / "data" / "manual_entity_overrides.csv"),
            "manual_url_overrides": str(root / "data" / "manual_url_overrides.csv"),
            "review_csv": str(root / "results" / "reference_review.csv"),
        }
        values.update(overrides)
        return SimpleNamespace(**values)

    def _write_inputs(self, root: Path) -> None:
        write_csv(
            root / "results" / "published-20260326" / "publishable_master_games.csv",
            [
                "normalized_title",
                "representative_title",
                "first_seen_issue",
                "issue_count",
                "occurrence_count",
                "best_confidence",
                "source_kinds",
                "game_id",
                "first_seen_year",
                "last_seen_issue",
                "last_seen_year",
                "alias_count",
                "alias_titles",
                "legacy_normalized_titles",
                "observed_content_kinds",
                "observed_content_forms",
                "content_class",
                "cleanup_flags",
                "merge_confidence",
                "match_status",
                "match_confidence",
                "canonical_title",
                "canonical_slug",
                "entity_type",
                "release_year",
                "wikipedia_url",
                "wikidata_id",
                "wikidata_url",
                "categories",
                "genres",
                "themes",
                "rating_value",
                "rating_scale",
                "rating_count",
                "rating_source",
                "rating_url",
                "metadata_sources",
                "match_action",
                "match_notes",
                "data_quality_score",
            ],
            [
                {
                    "normalized_title": "age of empires 3",
                    "representative_title": "Age Of Empires 3",
                    "first_seen_issue": "CBS022006DVD",
                    "issue_count": "1",
                    "occurrence_count": "2",
                    "best_confidence": "high",
                    "source_kinds": "disc-metadata-value",
                    "game_id": "ageofempires3",
                    "first_seen_year": "2006",
                    "last_seen_issue": "CBS022006DVD",
                    "last_seen_year": "2006",
                    "alias_count": "2",
                    "alias_titles": "Age of Empires 3 v 1; Age of Empires 3 v 1 01a",
                    "legacy_normalized_titles": "age of empires 3 v 1; age of empires 3 v 1 01a",
                    "observed_content_kinds": "unknown",
                    "observed_content_forms": "game_title",
                    "content_class": "game",
                    "cleanup_flags": "stripped_version_suffix",
                    "merge_confidence": "high",
                    "match_status": "unmatched",
                    "match_confidence": "low",
                    "canonical_title": "",
                    "canonical_slug": "",
                    "entity_type": "",
                    "release_year": "",
                    "wikipedia_url": "",
                    "wikidata_id": "",
                    "wikidata_url": "",
                    "categories": "",
                    "genres": "",
                    "themes": "",
                    "rating_value": "",
                    "rating_scale": "",
                    "rating_count": "",
                    "rating_source": "",
                    "rating_url": "",
                    "metadata_sources": "",
                    "match_action": "",
                    "match_notes": "",
                    "data_quality_score": "",
                },
                {
                    "normalized_title": "absolute blue",
                    "representative_title": "Absolute Blue",
                    "first_seen_issue": "CBS082005DVD",
                    "issue_count": "1",
                    "occurrence_count": "1",
                    "best_confidence": "high",
                    "source_kinds": "disc-metadata-value",
                    "game_id": "absoluteblue",
                    "first_seen_year": "2005",
                    "last_seen_issue": "CBS082005DVD",
                    "last_seen_year": "2005",
                    "alias_count": "1",
                    "alias_titles": "Absolute Blue",
                    "legacy_normalized_titles": "absolute blue",
                    "observed_content_kinds": "unknown",
                    "observed_content_forms": "game_title",
                    "content_class": "game",
                    "cleanup_flags": "",
                    "merge_confidence": "high",
                    "match_status": "unmatched",
                    "match_confidence": "low",
                    "canonical_title": "",
                    "canonical_slug": "",
                    "entity_type": "",
                    "release_year": "",
                    "wikipedia_url": "",
                    "wikidata_id": "",
                    "wikidata_url": "",
                    "categories": "",
                    "genres": "",
                    "themes": "",
                    "rating_value": "",
                    "rating_scale": "",
                    "rating_count": "",
                    "rating_source": "",
                    "rating_url": "",
                    "metadata_sources": "",
                    "match_action": "",
                    "match_notes": "",
                    "data_quality_score": "",
                },
            ],
        )
        write_csv(
            root / "results" / "published-20260326" / "publishable_issue_titles.csv",
            [
                "archive_item",
                "archive_name",
                "issue_code",
                "year",
                "variant",
                "normalized_title",
                "representative_title",
                "source_kinds",
                "confidence",
                "content_kind",
                "clean_reason",
                "game_id",
                "source_title",
                "source_normalized_title",
                "observed_title_variants",
                "source_normalized_variants",
                "occurrence_count_in_issue",
                "content_class",
                "content_form",
                "content_kinds_merged",
                "content_forms_merged",
                "cleanup_flags",
                "merge_confidence",
                "match_status",
                "match_confidence",
                "canonical_title",
                "canonical_slug",
                "entity_type",
                "release_year",
                "wikipedia_url",
                "wikidata_id",
                "wikidata_url",
                "categories",
                "genres",
                "themes",
                "match_action",
                "match_notes",
                "data_quality_score",
            ],
            [
                {
                    "archive_item": "cbs-2000-09",
                    "archive_name": "2006/CBS022006DVD.7z",
                    "issue_code": "CBS022006DVD",
                    "year": "2006",
                    "variant": "DVD",
                    "normalized_title": "age of empires 3",
                    "representative_title": "Age Of Empires 3",
                    "source_kinds": "disc-metadata-value",
                    "confidence": "high",
                    "content_kind": "unknown",
                    "clean_reason": "multiword",
                    "game_id": "ageofempires3",
                    "source_title": "Age of Empires 3 v 1",
                    "source_normalized_title": "age of empires 3 v 1",
                    "observed_title_variants": "Age of Empires 3 v 1; Age of Empires 3 v 1 01a",
                    "source_normalized_variants": "age of empires 3 v 1; age of empires 3 v 1 01a",
                    "occurrence_count_in_issue": "2",
                    "content_class": "game",
                    "content_form": "game_title",
                    "content_kinds_merged": "unknown",
                    "content_forms_merged": "game_title",
                    "cleanup_flags": "stripped_version_suffix",
                    "merge_confidence": "high",
                    "match_status": "unmatched",
                    "match_confidence": "low",
                    "canonical_title": "",
                    "canonical_slug": "",
                    "entity_type": "",
                    "release_year": "",
                    "wikipedia_url": "",
                    "wikidata_id": "",
                    "wikidata_url": "",
                    "categories": "",
                    "genres": "",
                    "themes": "",
                    "match_action": "",
                    "match_notes": "",
                    "data_quality_score": "",
                },
                {
                    "archive_item": "cbs-2000-09",
                    "archive_name": "2005/CBS082005DVD.7z",
                    "issue_code": "CBS082005DVD",
                    "year": "2005",
                    "variant": "DVD",
                    "normalized_title": "absolute blue",
                    "representative_title": "Absolute Blue",
                    "source_kinds": "disc-metadata-value",
                    "confidence": "high",
                    "content_kind": "unknown",
                    "clean_reason": "multiword",
                    "game_id": "absoluteblue",
                    "source_title": "Absolute Blue",
                    "source_normalized_title": "absolute blue",
                    "observed_title_variants": "Absolute Blue",
                    "source_normalized_variants": "absolute blue",
                    "occurrence_count_in_issue": "1",
                    "content_class": "game",
                    "content_form": "game_title",
                    "content_kinds_merged": "unknown",
                    "content_forms_merged": "game_title",
                    "cleanup_flags": "",
                    "merge_confidence": "high",
                    "match_status": "unmatched",
                    "match_confidence": "low",
                    "canonical_title": "",
                    "canonical_slug": "",
                    "entity_type": "",
                    "release_year": "",
                    "wikipedia_url": "",
                    "wikidata_id": "",
                    "wikidata_url": "",
                    "categories": "",
                    "genres": "",
                    "themes": "",
                    "match_action": "",
                    "match_notes": "",
                    "data_quality_score": "",
                },
            ],
        )
        write_csv(
            root / "results" / "enriched-20260325" / "enriched_master_games.csv",
            [
                "normalized_title",
                "representative_title",
                "first_seen_issue",
                "issue_count",
                "occurrence_count",
                "best_confidence",
                "source_kinds",
                "canonical_title",
                "canonical_slug",
                "match_status",
                "match_confidence",
                "match_method",
                "match_source",
                "match_source_url",
                "match_fetched_at",
                "entity_type",
                "release_year",
                "wikipedia_url",
                "wikidata_id",
                "wikidata_url",
                "categories",
                "genres",
                "themes",
                "category_source",
                "category_source_url",
                "category_fetched_at",
                "category_confidence",
                "rating_value",
                "rating_scale",
                "rating_count",
                "rating_source",
                "rating_url",
                "rating_fetched_at",
                "rating_confidence",
                "metadata_sources",
                "notes",
            ],
            [
                {
                    "normalized_title": "age of empires 3 v 1",
                    "representative_title": "Age of Empires 3 v 1",
                    "first_seen_issue": "CBS022006DVD",
                    "issue_count": "1",
                    "occurrence_count": "1",
                    "best_confidence": "high",
                    "source_kinds": "disc-metadata-value",
                    "canonical_title": "Age of Empires III: Definitive Edition",
                    "canonical_slug": "age-of-empires-iii-definitive-edition",
                    "match_status": "matched",
                    "match_confidence": "high",
                    "match_method": "wikidata-search",
                    "match_source": "wikimedia",
                    "match_source_url": "https://en.wikipedia.org/wiki/Age_of_Empires_III:_Definitive_Edition",
                    "match_fetched_at": "2026-03-25T00:00:00+00:00",
                    "entity_type": "game",
                    "release_year": "2020",
                    "wikipedia_url": "https://en.wikipedia.org/wiki/Age_of_Empires_III:_Definitive_Edition",
                    "wikidata_id": "Q1",
                    "wikidata_url": "https://www.wikidata.org/wiki/Q1",
                    "categories": "strategy",
                    "genres": "real-time strategy",
                    "themes": "",
                    "category_source": "wikidata",
                    "category_source_url": "https://www.wikidata.org/wiki/Q1",
                    "category_fetched_at": "2026-03-25T00:00:00+00:00",
                    "category_confidence": "high",
                    "rating_value": "",
                    "rating_scale": "",
                    "rating_count": "",
                    "rating_source": "",
                    "rating_url": "",
                    "rating_fetched_at": "",
                    "rating_confidence": "",
                    "metadata_sources": "wikidata",
                    "notes": "",
                },
                {
                    "normalized_title": "age of empires 3 v 1 01a",
                    "representative_title": "Age of Empires 3 v 1 01a",
                    "first_seen_issue": "CBS022006DVD",
                    "issue_count": "1",
                    "occurrence_count": "1",
                    "best_confidence": "high",
                    "source_kinds": "disc-metadata-value",
                    "canonical_title": "Age of Empires III: Definitive Edition",
                    "canonical_slug": "age-of-empires-iii-definitive-edition",
                    "match_status": "matched",
                    "match_confidence": "high",
                    "match_method": "wikidata-search",
                    "match_source": "wikimedia",
                    "match_source_url": "https://en.wikipedia.org/wiki/Age_of_Empires_III:_Definitive_Edition",
                    "match_fetched_at": "2026-03-25T00:00:00+00:00",
                    "entity_type": "game",
                    "release_year": "2020",
                    "wikipedia_url": "https://en.wikipedia.org/wiki/Age_of_Empires_III:_Definitive_Edition",
                    "wikidata_id": "Q1",
                    "wikidata_url": "https://www.wikidata.org/wiki/Q1",
                    "categories": "strategy",
                    "genres": "real-time strategy",
                    "themes": "",
                    "category_source": "wikidata",
                    "category_source_url": "https://www.wikidata.org/wiki/Q1",
                    "category_fetched_at": "2026-03-25T00:00:00+00:00",
                    "category_confidence": "high",
                    "rating_value": "",
                    "rating_scale": "",
                    "rating_count": "",
                    "rating_source": "",
                    "rating_url": "",
                    "rating_fetched_at": "",
                    "rating_confidence": "",
                    "metadata_sources": "wikidata",
                    "notes": "",
                },
                {
                    "normalized_title": "absolute blue",
                    "representative_title": "Absolute Blue",
                    "first_seen_issue": "CBS082005DVD",
                    "issue_count": "1",
                    "occurrence_count": "1",
                    "best_confidence": "high",
                    "source_kinds": "disc-metadata-value",
                    "canonical_title": "Q122386684",
                    "canonical_slug": "q122386684",
                    "match_status": "matched",
                    "match_confidence": "high",
                    "match_method": "wikidata-search",
                    "match_source": "wikimedia",
                    "match_source_url": "https://www.wikidata.org/wiki/Q122386684",
                    "match_fetched_at": "2026-03-25T00:00:00+00:00",
                    "entity_type": "game",
                    "release_year": "2018",
                    "wikipedia_url": "",
                    "wikidata_id": "Q122386684",
                    "wikidata_url": "https://www.wikidata.org/wiki/Q122386684",
                    "categories": "shooter",
                    "genres": "shooter game",
                    "themes": "",
                    "category_source": "wikidata",
                    "category_source_url": "https://www.wikidata.org/wiki/Q122386684",
                    "category_fetched_at": "2026-03-25T00:00:00+00:00",
                    "category_confidence": "high",
                    "rating_value": "",
                    "rating_scale": "",
                    "rating_count": "",
                    "rating_source": "",
                    "rating_url": "",
                    "rating_fetched_at": "",
                    "rating_confidence": "",
                    "metadata_sources": "wikidata",
                    "notes": "",
                },
            ],
        )
        data_dir = root / "data"
        data_dir.mkdir(parents=True, exist_ok=True)
        (data_dir / "manual_rejections.csv").write_text(
            "normalized_title,rejected_candidate,source,reason\n"
            "age of empires 3 v 1,Age of Empires III: Definitive Edition,wikimedia,matched the 2020 remaster instead of the original game\n"
            "age of empires 3 v 1 01a,Age of Empires III: Definitive Edition,wikimedia,matched the 2020 remaster instead of the original game\n"
            "absolute blue,Q122386684,wikimedia,matched a raw Wikidata placeholder label with a release-year conflict\n",
            encoding="utf-8",
        )
        for name in ["manual_alias_overrides.csv", "manual_entity_overrides.csv", "manual_url_overrides.csv"]:
            (data_dir / name).write_text("", encoding="utf-8")

    def test_builds_clustered_outputs_and_demotions(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            self._write_inputs(root)

            rc = run_build(self._args(root))
            self.assertEqual(rc, 0)

            out_dir = root / "results" / "enriched-20260326"
            master_rows = read_csv(out_dir / "enriched_master_games.csv")
            issue_rows = read_csv(out_dir / "enriched_issue_titles.csv")
            alias_rows = read_csv(out_dir / "title_aliases.csv")
            demotion_rows = read_csv(out_dir / "match_demotions.csv")

            age = next(row for row in master_rows if row["game_id"] == "ageofempires3")
            absolute = next(row for row in master_rows if row["game_id"] == "absoluteblue")

            self.assertEqual(age["match_status"], "unmatched")
            self.assertEqual(age["match_action"], "demoted_weak_alias_match")
            self.assertIn("demoted_release_year_conflict", age["match_notes"])
            self.assertEqual(absolute["match_status"], "unmatched")
            self.assertIn("demoted_raw_qid_title", absolute["match_notes"])
            self.assertEqual(issue_rows[0]["game_id"], "absoluteblue")
            self.assertTrue(any(row["game_id"] == "ageofempires3" for row in alias_rows))
            self.assertEqual(len(demotion_rows), 2)
            self.assertTrue((out_dir / "enrichment_audit.md").exists())

    def test_repeat_run_is_deterministic(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            self._write_inputs(root)

            run_build(self._args(root))
            first = (root / "results" / "enriched-20260326" / "enriched_master_games.csv").read_text(encoding="utf-8")
            run_build(self._args(root))
            second = (root / "results" / "enriched-20260326" / "enriched_master_games.csv").read_text(encoding="utf-8")
            self.assertEqual(first, second)
